# Generated by Django 6.1 on 2026-08-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='cotegory',
            new_name='category',
        ),
    ]
